### ISSUE TITLE
로직 설명 부탁드립니다!

### ISSUE THREAD

**Issue by Gwonyeong** [dailythm/dailythm-ryeong#1]
[피자 나눠 먹기](https://github.com/dailythm/dailythm-ryeong/blob/main/Programmers/CodingTest-basic/python/Day-04/013.%ED%94%BC%EC%9E%90_%EB%82%98%EB%88%A0_%EB%A8%B9%EA%B8%B0(1).py)

제가 이해한 바 문제는 "7조각으로 나누는 피자를 n명이 한 조각 이상 먹으려면 피자가 몇 판이 필요할까?" 라고 이해를 했는데 작성해 주신 로직의 원리를 저는 이해하지 못하겠습니다. 

n이 7로 나눠떨어지지 않는다면 n을 7+1로 나눠 몫을 구하시는걸로 보입니다.

예를 들어 인원이 8명이라고 하면 피자는 2판이 필요하게 되는 상황에서 8을 7+1로 나누어 버리면 1이라는 숫자가 나와버리지 않을까요? 

제가 이해한게 맞는지 용선생님께 여쭤보고 싶습니다.

**Comment by sumin-dev** [comment]
제가 이해한 대로 성령님의 코드를 풀이해 보자면
```python
def solution(n):
    if n % 7 == 0:
        return n // 7
    else:
        return n // 7 + 1
```
연산의 순서를 헷갈리신 듯 합니다! else문에서 n을 7로 나눈 몫에 +1을 하는 것 같습니다.
괄호를 사용해서 표현하면 return (n // 7) + 1입니다!
이슈로 질문하는 방식 너무 좋은 것 같아요 @kwanyung 님(✿◕‿◕✿)

**Comment by Gwonyeong** [comment]
부끄러우니 얼른 close 하겠습니다.
